#This is not pushed to a public repo in production projects, secrets are applied directly to k8s cluster for
#whatever infrastructure being used.
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  pg-root-username: ZGFyZQ==
  pg-root-password: cGFzc3dvcmQ=
  pg-root-db: dGVzdHM=
  pg-db: dGFza21hbmFnZW1lbnQ=
  pgadmin-password: U3VwZXJTZWNyZXQ=
  pgadmin-email: ZGFyZS5mYWxvbGE3QGdtYWlsLmNvbQ==
  jwt-secret: dG9wU2VjcmV0MTAx
