{{- define "deployment" -}}
{{- if not .Values.ingress.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "microservice.fullname" . }}
  {{- if .Values.annotations }}
  annotations:
  {{- range $key, $value := .Values.annotations }}
    {{ $key }}: {{ $value }}
  {{- end }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "microservice.name" . }}
    helm.sh/chart: {{ include "microservice.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount | default .Values.global.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "microservice.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "microservice.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      {{- if .Values.serviceAccount }}
      serviceAccountName: {{ .Values.serviceAccount }}
      {{- end }}
      {{- if .Values.hostAliases }}
      hostAliases:
      {{- range .Values.hostAliases }}
      - ip: {{ .ip }}
        hostnames:
        {{- range .hostnames }}
        - {{ . }}
        {{- end }}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imageConfig.pullPolicy }}
          {{- if .Values.command }}
          command: {{ .Values.command }}
          {{- end }}
          {{- if .Values.args }}
          args: [ {{- range .Values.args }}{{ cat ( . | quote ) ","  }}{{- end }} ]
          {{- end }}
          ports:
            {{- with first .Values.services -}}
            {{- range $port:= .specs}}
            - name: {{ .name }}
              containerPort: {{ .targetPort | default .port}}
              protocol: {{ .protocol | default "TCP" }}
            {{- end }}
            {{- end }}
          {{- if not ( empty .Values.environment) }}
          env:
            {{- range .Values.environment }}
            - name: {{ .name }}
              {{- if .value }}
              value: {{ .value }}
              {{- else if .valueFrom }}
              valueFrom:
                {{- if .valueFrom.secretKeyRef }}
                secretKeyRef:
                  name: {{ .valueFrom.secretKeyRef.name }}
                  key: {{ .valueFrom.secretKeyRef.key }}
                {{- else if .valueFrom.configMapKeyRef }}
                configMapKeyRef:
                  name: {{ .valueFrom.configMapKeyRef.name }}
                  key: {{ .valueFrom.configMapKeyRef.key }}
                {{- else }}
                fieldRef:
                  fieldPath: metadata.name
                {{- end }}
              {{- end }}
            {{- end }}
          {{- end }}
          {{- if .Values.volumes.enabled }}
          volumeMounts:
            {{- range $conf := .Values.volumes.configMaps }}
            - mountPath: {{ $conf.mountPath }}
              name: {{ $conf.name }}-volume
            {{- end }}
            {{- range .Values.fileConfigMap }}
            - mountPath: {{ .mountPath }}
              name: {{ .volumeName }}-volume
            {{- end }}
            {{- if .Values.volumes.pvc.enabled }}
            - mountPath: {{ .Values.volumes.pvc.mountPath }}
              name: {{ .Values.volumes.pvc.existing_claim | default .Values.volumes.pvc.name }}-volume
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- range .Values.initContainers }}
      initContainers:
        - name: {{ .name }}
          image: {{ .image }}
          command:
          {{- range $arg := .command }}
            - {{ $arg | quote }}
          {{- end }}
          volumeMounts:
            - mountPath: {{ .volumeMount.mountPath }}
              name: {{ .volumeMount.name }}
      {{- end }}
      {{- if .Values.volumes.enabled }}
      volumes:
        {{- range $conf := .Values.volumes.configMaps }}
        - name: {{ $conf.name }}-volume
          configMap:
            name: {{ $conf.name }}
       {{- end }}
       {{- if .Values.volumes.pvc.enabled}}
        - name: {{ .Values.volumes.pvc.existing_claim | default .Values.volumes.pvc.name }}-volume
          persistentVolumeClaim:
            claimName: {{ .Values.volumes.pvc.existing_claim | default .Values.volumes.pvc.name }}
       {{- end}}
       {{- range .Values.fileConfigMap }}
        - name: {{ .volumeName }}-volume
          configMap:
            name: {{ .name }}
      {{- end }}
      {{- end }}
{{- end -}}
{{- end -}}